# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel-starter-v2.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        ports:
          - "8084:80"
        expose:
            - 80
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            VIRTUAL_HOST: laravel-starter-v2.test
            VIRTUAL_PORT: 80
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
            - nginx-proxy
        depends_on:
            - mysql
    mysql:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "mysqladmin", "ping"]
networks:
    sail:
        driver: bridge
    nginx-proxy:
        external: true
volumes:
    sailmysql:
        driver: local
