<?php

view()->share('Política de Cookies');
view()->share('hideSubHeader', true);
?>
<x-auth-layout>
    <h3>Política de Cookies</h3>
    <p>Atualizado a 7 de janeiro de 2021</p>
    <br />
    <p>Este website recorre ao uso de cookies para proporcionar uma melhor utilização pelos seus visitantes, bem como para assegurar que o mesmo se encontra em pleno funcionamento. Esta Política de cookies faz parte da nossa <a href="{{ route('policies.privacy_policy') }}">Política de Privacidade</a>. Para mais informações sobre nós e sobre a forma como protegemos as informações dos utilizadores consulte a nossa <a href="{{ route('policies.privacy_policy') }}">Política de Privacidade</a>. De modo a disponibilizarmos um serviço personalizado e eficiente aos nossos utilizadores torna-se necessário memorizar e armazenar informação sobre a forma como este Website deve ser utilizado. Para tal, utilizamos ficheiros de texto reduzido denominados por cookies que contêm quantidades de informação reduzidas descarregadas para o computador ou outros dispositivos dos nossos utilizadores através de um servidor. O seu browser de internet posteriormente envia, em cada visita subsequente, estas cookies de volta para o Website, permitindo o reconhecimento e memorização da identidade dos nossos visitantes, designadamente as preferências de utilização dos nossos utilizadores. Poderá encontrar aqui (aboutcookies.org) informação mais detalhada sobre cookies e seu respetivo funcionamento. A navegação neste Website permite a recolha de informação com recurso a cookies e demais tecnologias. Ao usar este site aceita o uso de cookies tal como descrito nesta Notificação de cookies.</p>
    <br />
    <h4>Quais os tipos de cookies utilizados e porquê?</h4>
    <p>Parte das cookies a que recorremos são necessárias para permitir a navegação neste website bem como tirar partido das suas funcionalidades tais como aceder a áreas seguras e conteúdos de acesso exclusivo para utilizadores registados. O nosso website também recorre ao uso de cookies funcionais para gravar informação sobre as opções dos nossos utilizadores e permitir adaptar o nosso website às necessidades dos mesmos; por exemplo, memorizar a língua de origem ou região ou que um utilizador já completou o preenchimento de um inquérito. A informação gravada é anónima e destina-se apenas ao fim acima indicado. Podemos utilizar, direta ou indiretamente, serviços de web analytics para aferir a eficácia dos nossos conteúdos e as preferências dos nossos utilizadores que nos permitem contribuir para a otimização do funcionamento deste website. Adicionalmente, recorremos aos web beacons ou tracking pixels para contabilizar o número de visitantes e as cookies de desempenho  para monitorizar a forma como os utilizadores individualmente acedem ao nosso website e com que regularidade. Esta informação é usada apenas para efeitos estatísticos sem identificação de qualquer utilizador em particular. No entanto, para utilizadores registados que estejam conectados ao website poderemos proceder ao uso combinado desta informação com os dados recolhidos via serviços de web analytics e a cookies para analisar a forma como os visitantes utilizam este website em mais pormenor. Este website não recorre à utilização de targeting cookies para promover publicidade direcionada aos nossos visitantes. Sempre que pretendam informação detalhada sobre as cookies utilizadas no nosso website agradecemos o vosso contacto através do <a href="https://www.apap.pt/contactos/">formulário de email</a>.</p>
    <br />
    <h4>Como controlar as cookies?</h4>
    <p>Os utilizadores do website aceitam a introdução das cookies nos seus computadores ou dispositivos nos termos acima indicados sem prejuízo do controle e gestão disponíveis. Informamos os utilizadores que a remoção ou bloqueio das cookies poderá afetar a sua experiência de utilização e poderá limitar o acesso a algumas zonas do website.</p>
    <br />
    <h4>Controlos no browser</h4>
    A grande maioria dos browsers permite aos nossos utilizadores visualizar as cookies alojadas e eliminá-las individualmente ou alternativamente bloquear as cookies num determinado website ou todos em geral. Lembramos que as preferências definidas, incluindo auto-exclusão, são perdidas sempre que as cookies sejam eliminadas. Para mais esclarecimentos devem consultar os websites ou <a href="http://www.cookiecentral.com/faq/">cookiecentral.com</a>.
    <br />
    <h4>Gestão de analytics cookies</h4>
    <p>Os nossos utilizadores poderão escolher excluir o seu anonimato na sua atividade de navegação dentro dos websites monitorizados por analytics cookies. Nós usamos os seguintes prestadores de serviços onde poderão obter mais informações sobre as políticas de privacidade dos mesmos e como excluir as suas cookies clicando nos seguintes links:</p>
    <ul>
        <li>Google Analytics: google.com/analytics/learn/privacy.html</li>
        <li>Facebook Pixel: facebook.com/business/help/742478679120153</li>
    </ul>
    <br />
    <h4>Gestão de local shared objects ou flash cookies</h4>
    <p>Um local shared object ou flash cookie assemelha-se às restantes browser cookies, diferenciando-se pelo facto de conseguirem armazenar mais tipos de informação. Estas cookies não poderão ser controladas através dos mecanismos identificados acima. Algumas zonas do nosso website recorrem a este tipo de cookies para armazenar preferências do utilizador para as funcionalidades do media player e sem as mesmas o conteúdo de alguns vídeos não poderá ser visualizado de forma apropriada. Estas cookies poderão ser controladas manualmente visitando o <a href="http://www.macromedia.com/support/documentation/en/flashplayer/help/settings_manager07.html">website da Adobe</a>.</p>
    <br />
    <h4>Social buttons</h4>
    <p>Nós recorremos ao uso de social buttons para permitir aos nossos utilizadores partilharem ou adicionarem páginas aos favoritos. Estes botões são relativos a redes sociais as quais poderão obter informações sobre as atividades dos nossos visitantes na Internet, incluindo sobre o nosso website. O entendimento do modo como a informação é utilizada e como podem ser excluídos da sua recolha deve ser obtido através da revisão dos respetivos Termos de Utilização e Políticas de Privacidade desses websites.</p>
    <br />
    <h4>Comunicações via email</h4>
    <p>Para aferir a pertinência das nossas comunicações podemos usar tecnologias de monitorização para determinar se os nossos visitantes leram, clicaram em links ou reencaminharam determinadas comunicações através de email por nós enviadas. Em caso de desacordo com esse modo de proceder os nossos utilizadores devem reverter a sua subscrição (unsubscribe) dado que não é possível enviar estes emails sem estes mecanismos de monitorização ativos. Os subscritores registados podem atualizar as suas preferências de comunicação a qualquer momento contactando-nos através deste <a href="https://www.apap.pt/contactos/">formulário de email</a>, ou podem cancelar a sua subscrição, seguindo as instruções no email de comunicação por nós enviado para o seu endereço eletrónico.</p>
    <p>Esta Política de cookies pode ser revista a qualquer momento, de acordo com o nosso critério. Quando se fizerem tais alterações, a data de revisão no topo da página será alterada. A Política de cookies alterada entrará em vigor a partir da data de revisão. Recomendamos os utilizadores do nosso website que revejam as Políticas de cookies periodicamente, com o propósito de ficarem informados sobre a nossa gestão das cookies.</p>
</x-auth-layout>
